const target=new Date('2026-09-09T18:00:00+06:00').getTime();
function tick(){const d=Math.max(0,target-Date.now());const vals=[Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(vals[i]).padStart(i?2:3,'0'))}tick();setInterval(tick,1000);
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
const rsvpForm=document.getElementById('rsvpForm');
if(rsvpForm){rsvpForm.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('.submit'),success=document.getElementById('formSuccess');success.classList.remove('show','form-error');success.textContent='';button.disabled=true;button.classList.add('is-loading');try{const response=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});let result={};try{result=await response.json()}catch(_error){}if(response.status!==200||result.ok!==true)throw new Error(result.message||'Не удалось отправить ответ. Попробуйте ещё раз.');success.textContent='Спасибо! Ваш ответ отправлен ♡';success.classList.add('show');button.textContent='Ответ отправлен ✓';}catch(error){success.textContent=error instanceof TypeError?'Не удалось подключиться. Проверьте интернет и попробуйте ещё раз.':(error.message||'Не удалось отправить ответ. Попробуйте ещё раз.');success.classList.add('show','form-error');button.disabled=false;}finally{button.classList.remove('is-loading')}})}
const collage=document.querySelector('[data-tilt]');
if(collage && matchMedia('(pointer:fine)').matches){collage.addEventListener('pointermove',e=>{const r=collage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;collage.style.transform=`perspective(900px) rotateY(${x*4}deg) rotateX(${y*-4}deg)`;collage.querySelector('.hero-image-float').style.transform=`translate(${x*9}px,${y*9}px) rotate(-5deg)`});collage.addEventListener('pointerleave',()=>{collage.style.transform='';collage.querySelector('.hero-image-float').style.transform=''})}
const parallaxImages=[...document.querySelectorAll('[data-parallax]')];let scrollTick=false;if(parallaxImages.length){addEventListener('scroll',()=>{if(!scrollTick){requestAnimationFrame(()=>{parallaxImages.forEach(img=>{const wrap=img.closest('.hero-collage');if(!wrap)return;const r=wrap.getBoundingClientRect(),shift=Math.max(-20,Math.min(20,(innerHeight/2-r.top)*Number(img.dataset.parallax)));img.style.transform=`translate3d(0,${shift}px,0)`});scrollTick=false});scrollTick=true}},{passive:true})}
if('serviceWorker' in navigator) addEventListener('load',()=>{navigator.serviceWorker.getRegistrations().then(regs=>regs.forEach(reg=>reg.unregister()));if(window.caches) caches.keys().then(keys=>keys.forEach(key=>caches.delete(key)))});
document.querySelectorAll('main img:not(.hero-original-photo img)').forEach(img=>{img.loading='lazy';img.decoding='async'});
